export const BUSINESS_CATEGORIES = [
  { label: 'Restaurant', value: 'restaurant', query: 'Restaurant' },
  { label: 'Cafe / Bakery', value: 'cafe', query: 'Cafe Bäckerei' },
  { label: 'Hotel / Pension', value: 'hotel', query: 'Hotel Pension' },
  { label: 'Doctor / Arztpraxis', value: 'doctor', query: 'Arztpraxis Allgemeinmedizin' },
  { label: 'Dentist / Zahnarzt', value: 'dentist', query: 'Zahnarzt Zahnarztpraxis' },
  { label: 'Hairdresser / Friseur', value: 'hairdresser', query: 'Friseur Friseursalon' },
  { label: 'Car Workshop / Autowerkstatt', value: 'car_repair', query: 'Autowerkstatt KFZ' },
  { label: 'Real Estate / Immobilien', value: 'realestate', query: 'Immobilienmakler Immobilien' },
  { label: 'Insurance / Versicherung', value: 'insurance', query: 'Versicherungsmakler Versicherung' },
  { label: 'Tax Advisor / Steuerberater', value: 'tax', query: 'Steuerberater Steuerberatung' },
  { label: 'Lawyer / Rechtsanwalt', value: 'lawyer', query: 'Rechtsanwalt Kanzlei' },
  { label: 'Physiotherapy / Physiotherapeut', value: 'physiotherapy', query: 'Physiotherapeut Physiotherapie' },
  { label: 'Gym / Fitnessstudio', value: 'gym', query: 'Fitnessstudio Gym' },
  { label: 'Pharmacy / Apotheke', value: 'pharmacy', query: 'Apotheke' },
  { label: 'Electrician / Elektriker', value: 'electrician', query: 'Elektriker Elektrikbetrieb' },
  { label: 'Plumber / Klempner', value: 'plumber', query: 'Klempner Sanitär Heizung' },
  { label: 'Painter / Maler', value: 'painter', query: 'Maler Malerbetrieb' },
  { label: 'Photographer / Fotograf', value: 'photographer', query: 'Fotograf Fotostudio' },
  { label: 'Advertising Agency', value: 'agency', query: 'Werbeagentur Marketing Agentur' },
  { label: 'Accountant / Buchhalter', value: 'accountant', query: 'Buchhalter Buchhaltung' },
  { label: 'Vet / Tierarzt', value: 'vet', query: 'Tierarzt Tierarztpraxis' },
  { label: 'Optician / Optiker', value: 'optician', query: 'Optiker Augenoptiker' },
  { label: 'Cleaning / Reinigung', value: 'cleaning', query: 'Reinigungsunternehmen Gebäudereinigung' },
  { label: 'Travel Agency / Reisebüro', value: 'travel', query: 'Reisebüro Reiseagentur' },
  { label: 'Language School / Sprachschule', value: 'language', query: 'Sprachschule Sprachkurs' },
  { label: 'Flower Shop / Blumenladen', value: 'florist', query: 'Blumenladen Blumenhändler' },
  { label: 'Jewelry / Schmuck', value: 'jewelry', query: 'Juwelier Schmuckgeschäft' },
  { label: 'Moving Company / Umzug', value: 'moving', query: 'Umzugsunternehmen Umzugsfirma' },
  { label: 'Printing / Druckerei', value: 'printing', query: 'Druckerei Digitaldruck' },
  { label: 'IT Services / IT Dienstleistungen', value: 'it', query: 'IT Service IT Dienstleistungen' },
];
